image:
    name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  YC_SERVICE_ACCOUNT_KEY_FILE: /tmp/sa-key.json

before_script:
    - |
      cat <<EOF >> ~/.terraformrc
      provider_installation {
        network_mirror {
            url = "https://terraform-mirror.yandexcloud.net/"
            include = ["registry.terraform.io/*/*"]
        }
        direct {
            exclude = ["registry.terraform.io/*/*"]
        }
      }
      EOF
    - terraform init
    - echo $YC_KEY > /tmp/sa-key.json

stages:          # List of stages for jobs, and their order of execution
  - validate
  - plan
  - apply

validate:
    stage: validate
    script:
        - terraform validate

plan:
    stage: plan
    script:
        - terraform plan -out="planfile"
    artifacts:
      paths:
        - planfile

apply:
    stage: apply
    script:
        - terraform apply -auto-approve "planfile"
    artifacts:
        paths:
          - "inventory.ini"
          - "k8s-cluster.yml"
