# output "bucket_name" {
#   description = "The name of the bucket."
#   value       = module.s3.bucket_name
# }

# output "storage_admin_service_account_id" {
#   description = "Service account ID of the Object storage admin."
#   value       = module.s3.storage_admin_service_account_id
# }

# output "storage_admin_access_key" {
#   description = "Static access key of the autogenerated Object storage admin service account."
#   value       = module.s3.storage_admin_access_key
# }

# output "storage_admin_secret_key" {
#   description = "Static secret key of the autogenerated Object storage admin service account."
#   sensitive   = true
#   value       = module.s3.storage_admin_secret_key
# }

# output "sa-auth-key_created_at" {
#   description = "The name of the bucket."
#   value       = yandex_iam_service_account_key.sa-auth-key.created_at
# }

# output "sa-auth-key_id" {
#   description = "The name of the bucket."
#   value       = yandex_iam_service_account_key.sa-auth-key.id
# }

# output "sa-auth-key_key_algorithm" {
#   description = "The name of the bucket."
#   value       = yandex_iam_service_account_key.sa-auth-key.key_algorithm
# }

# output "sa-auth-key_key_fingerprint" {
#   description = "The name of the bucket."
#   value       = yandex_iam_service_account_key.sa-auth-key.key_fingerprint
# }

# output "sa-auth-key_private_key" {
#   description = "The name of the bucket."
#   value       = yandex_iam_service_account_key.sa-auth-key.private_key
#   sensitive = true
# }

# output "sa-auth-key_public_key" {
#   description = "The name of the bucket."
#   value       = yandex_iam_service_account_key.sa-auth-key.public_key
# }

# output "sa-auth-key_service_account_id" {
#   description = "The name of the bucket."
#   value       = yandex_iam_service_account_key.sa-auth-key.service_account_id
# }

